[package]
name = "ion-cli"
version = "0.1.0"
authors = ["The Ion Team <ion-team@amazon.com>"]
edition = "2018"
description = "Command line tool for working with the Ion data format."
repository = "https://github.com/amzn/ion-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
libc = "0.2"

[build-dependencies]
cmake = "0.1.44"

[[bin]]
name = "ion"
test = false
bench = false

