[package]
name = "ion-cli"
version = "0.1.0"
authors = ["Zack Slayton <zslayton@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"

[build-dependencies]
cmake = "0.1.44"
